import 'package:freezed_annotation/freezed_annotation.dart';

part 'github_failure.freezed.dart';

@freezed
class GithubFailure with _$GithubFailure {
    ///
    /// failure is a union class generated by the freezed package and
    /// that class contains all the failure cases in the app
    /// 
    const GithubFailure._();
    const factory GithubFailure.api(int? errorCode) = _Api;
}