import 'package:flutter/material.dart';
import 'package:repo_viewer/core/presentation/routes/app_router.gr.dart';
import 'package:repo_viewer/utils/app_constants.dart';

class AppWidget extends StatelessWidget {
    final appRouter = AppRouter();

    @override
    Widget build(BuildContext context) {
        ///
        /// to define the routes in the app using the auto route package:
        /// use the .router() and give it the router delegate and the router information parser
        /// using the app routes class that is generated by the package not the class we created
        ///
        return MaterialApp.router(
            title: AppConstants.appName,
            routerDelegate: appRouter.delegate(),
            routeInformationParser: appRouter.defaultRouteParser(),
        );
    }
}